### ISSUE TITLE
Add User Sign-out Functionality

### ISSUE THREAD

**Issue by kyllo34** [Coders-Living-Instant-Work-Journal/coders-living-instant-journal-api#8]
As a user I would, I want to be able to sign out of my session.

### Description
**When** the server receives a command to sign out
**Then**  the user access token is revoked

### Feature Task
- [ ] Write test cases for expected results
- [ ] Post route for sign out

### Acceptance Tests
- [ ] Passes test cases
- [ ] The user access token is revoked

**Comment by eugenemonnier** [comment]
Closing as this will be handled on the client side only. (for now)
